export const pendingData = [
  {
    id: "60d5ecb44b93bd113a479ad5",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org1",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 1",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org2",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 2",
  },
  {
    id: "60d5ecb44b93bd113a479ad3",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org3",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 3",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org4",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad4",
    title: "Donation 4",
  },
  // {
  //   _id: "2",
  //   fullName: "Jane Smith",
  //   email: "janesmith@example.com",
  //   role: "User",
  //   createdAt: new Date(),
  // },
  // Add more sample data objects as needed
]

export const assignedData = [
  {
    id: "60d5ecb44b93bd113a479ad5",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org1",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "assigned",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 1",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org2",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 2",
  },
  {
    id: "60d5ecb44b93bd113a479ad3",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org3",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 3",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org4",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "pending",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad4",
    title: "Donation 4",
  },
  // {
  //   _id: "2",
  //   fullName: "Jane Smith",
  //   email: "janesmith@example.com",
  //   role: "User",
  //   createdAt: new Date(),
  // },
  // Add more sample data objects as needed
]

export const completedData = [
  {
    id: "60d5ecb44b93bd113a479ad5",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org1",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "completed",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 1",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org2",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "completed",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 2",
  },
  {
    id: "60d5ecb44b93bd113a479ad3",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org3",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "completed",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 3",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org4",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "completed",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad4",
    title: "Donation 4",
  },
  // {
  //   _id: "2",
  //   fullName: "Jane Smith",
  //   email: "janesmith@example.com",
  //   role: "User",
  //   createdAt: new Date(),
  // },
  // Add more sample data objects as needed
]
export const cancelledData = [
  {
    id: "60d5ecb44b93bd113a479ad5",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org1",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "cancelled",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 1",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org2",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "cancelled",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 2",
  },
  {
    id: "60d5ecb44b93bd113a479ad3",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org3",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "cancelled",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
    title: "Donation 3",
  },
  {
    id: "60d5ecb44b93bd113a479ad7",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "Org4",
    donationDate: "2022-01-01T00:00:00.000Z",
    dateSubmitted: "2022-01-01T00:00:00.000Z", // Added dateSubmitted
    organization: "Local Food Bank",
    donorStatus: "cancelled",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad4",
    title: "Donation 4",
  },
  // {
  //   _id: "2",
  //   fullName: "Jane Smith",
  //   email: "janesmith@example.com",
  //   role: "User",
  //   createdAt: new Date(),
  // },
  // Add more sample data objects as needed
]
