export const sampleData = [
  {
    id: "60d5ecb44b93bd113a479ad5",
    donorId: "60d5ecb44b93bd113a479ad6",
    organizationId: "60d5ecb44b93bd113a479ad7",
    donationDate: "2022-01-01T00:00:00.000Z",
    organization: "Local Food Bank",
    donorStatus: "submitted",
    organizationStatus: "Received",
    donationType: "Food",
    donationValue: 100.0,
    donationDetails: "Canned goods and fresh produce",
    pickupAddress: "123 Main St, Anytown, USA",
    notificationStatus: false,
    cancellationReason: null,
    completionDate: null,
    donorContactInfo: "donor@example.com",
    organizationContactInfo: "organization@example.com",
    donationPickupInstructions: "Pick up from front porch",
    donorFeedback: null,
    organizationFeedback: null,
    userId: "60d5ecb44b93bd113a479ad8",
  },
  // {
  //   _id: "2",
  //   fullName: "Jane Smith",
  //   email: "janesmith@example.com",
  //   role: "User",
  //   createdAt: new Date(),
  // },
  // Add more sample data objects as needed
]
